test

diff --git a/.github/workflows/pipeline-update-shop.yml b/.github/workflows/pipeline-update-shop.yml
--- a/.github/workflows/pipeline-update-shop.yml
+++ b/.github/workflows/pipeline-update-shop.yml
@@ -106,20 +106,20 @@ jobs:
           --output text)
         echo "public_ip=$public_ip"
 
-    # - name: Write EC2 private key
-    #   run: echo "${{ secrets.AWS_EC2_PRIVATE_KEY }}" > ./ec2-key.pem && chmod 600 ./ec2-key.pem
+    - name: Write EC2 private key
+      run: echo "${{ secrets.AWS_EC2_PRIVATE_KEY }}" > ./ec2-key.pem && chmod 600 ./ec2-key.pem
 
-    # - name: Run InSpec test on EC2
-    #   run: |
-    #     set -e
-    #     CHEF_LICENSE=accept inspec exec inspec-profile/controls/image-base.rb \
-    #       -t ssh://ubuntu@${{ steps.get_ip.outputs.public_ip }} \
-    #       --key-files ./ec2-key.pem
+    - name: Run InSpec test on EC2
+      run: |
+        set -e
+        CHEF_LICENSE=accept inspec exec inspec-profile/controls/image-base.rb \
+          -t ssh://ubuntu@${{ steps.get_ip.outputs.public_ip }} \
+          --key-files ./ec2-key.pem
 
-    # - name: Terminate EC2 instance
-    #   if: always() # Ensures termination even if previous steps fail
-    #   run: |
-    #     aws ec2 terminate-instances --instance-ids ${{ steps.ec2_launch.outputs.instance_id }}
+    - name: Terminate EC2 instance
+      if: always() # Ensures termination even if previous steps fail
+      run: |
+        aws ec2 terminate-instances --instance-ids ${{ steps.ec2_launch.outputs.instance_id }}
 
   # distribute-image:
   #   name: Distribute golden image
